-- Create a table for public profiles
create table profiles (
  id uuid references auth.users on delete cascade not null primary key,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  username text unique,
  firstname text,
  lastname text,
  email text unique

  constraint username_length check (char_length(username) >= 3)
);
-- Set up Row Level Security (RLS)
-- See https://supabase.com/docs/guides/auth/row-level-security for more details.
alter table profiles
  enable row level security;

create policy "Public profiles are viewable by everyone." on profiles
  for select using (true);

create policy "Users can insert their own profile." on profiles
  for insert with check (auth.uid() = id);

create policy "Users can update own profile." on profiles
  for update using (auth.uid() = id);

-- This trigger automatically creates a profile entry when a new user signs up via Supabase Auth.
-- See https://supabase.com/docs/guides/auth/managing-user-data#using-triggers for more details.
create function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, username, email)
  values (new.id, new.raw_user_meta_data->>'user_name', new.email);
  return new;
end;
$$ language plpgsql security definer;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Set up Storage!
insert into storage.buckets (id, name)
  values ('avatars', 'avatars');

-- Set up access controls for storage.
-- See https://supabase.com/docs/guides/storage#policy-examples for more details.
create policy "Avatar images are publicly accessible." on storage.objects
  for select using (bucket_id = 'avatars');

create policy "Anyone can upload an avatar." on storage.objects
  for insert with check (bucket_id = 'avatars');

-- Create a table for public articles
create table articles (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text,
  content text,
  author uuid
);

alter table articles
  enable row level security;

create policy "Articles are viewable by everyone." on articles
  for select using (true);

create policy "Users can edit their own articles." on articles
  for update using (auth.uid() = author);

create policy "Users can delete their own articles." on articles
  for delete using (auth.uid() = author);

create policy "Users can insert articles." on articles
  for insert to authenticated with check (true);

create table comments (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  article_id bigint references articles (id),
  author uuid,
  message text
);

alter table comments
  enable row level security;

create policy "Comments are viewable by everyone." on comments
  for select using (true);

create policy "Users can edit their own comments." on comments
  for update using (auth.uid() = author);

create policy "Users can delete their own comments." on comments
  for delete using (auth.uid() = author);

create policy "Users can insert comments." on comments
  for insert to authenticated with check (true);

create table contacts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  firstname text,
  lastname text,
  email text,
  message text
);

INSERT INTO contacts (firstname, lastname, email, message) VALUES
  ('david', 'worms', 'david@adaltas.com', E'# Hello\nHope you are enjoying the course.');