// import { Auth, ThemeSupa } from '@supabase/auth-ui-react'
// import { useSession, useSupabaseClient } from '@supabase/auth-helpers-react'
// import Account from '../components/Account.js'
// import { createClient } from '@supabase/supabase-js'

// const login = () => {
//   const session = useSession()
//   const supabase = useSupabaseClient()
//   // const supabase = createClient(
//   //   process.env.NEXT_PUBLIC_SUPABASE_URL,
//   //   process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY
//   // )
//   return (
//     <div className="container" style={{ padding: '50px 0 100px 0' }}>
//       {!session ? (
//         <Auth providers={['github']} supabaseClient={supabase} appearance={{ theme: ThemeSupa }} theme="dark" />
//       ) : (
//         // <Account session={session} />
//         <button className="button block" onClick={() => supabase.auth.signOut()}>
//           Sign Out
//         </button>
//       )}
//     </div>
//   )
// }

// export default login

// import { createClient } from '@supabase/supabase-js'
// import { Auth } from '@supabase/auth-ui-react'
// import { useSession, useSupabaseClient } from '@supabase/auth-helpers-react'

// const supabase = createClient(
//   process.env.NEXT_PUBLIC_SUPABASE_URL,
//   process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY
// )
// const App = () => {
//     const session = useSession()
  
//     return (
//       <div className="container" style={{ padding: '50px 0 100px 0' }}>
//         {!session ? (
//           <Auth providers={['github']} supabaseClient={supabase}/>
//         ) : (
//           // <Account session={session} />
//           <button className="button block" onClick={() => supabase.auth.signOut()}>
//             Sign Out
//           </button>
//         )}
//       </div>
//     )
//   }
//   // }<Auth supabaseClient={supabase} />

// export default App


// import { createClient } from '@supabase/supabase-js'
// import { Auth } from '@supabase/auth-ui-react'
// import { useSession, useSupabaseClient } from '@supabase/auth-helpers-react'
// import Account from '../components/Account'

// const login = () => {
//   const session = useSession()
//   // const supabase = createClient(
//   //   process.env.NEXT_PUBLIC_SUPABASE_URL,
//   //   process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY
//   // )
//   const supabase = useSupabaseClient()

//   return (
//     <div>
//       {!session ? (
//         <Auth providers={['github']} supabaseClient={supabase}/>
//       ) : (
//         <button className="button block" onClick={() => supabase.auth.signOut()}>
//           Sign Out
//         </button>
//       )}
//     </div>
//   )
// }

// export default login


// import { createClient } from '@supabase/supabase-js'
// import { Auth } from '@supabase/auth-ui-react'

// const supabase = createClient(
//   process.env.NEXT_PUBLIC_SUPABASE_URL,
//   process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY
// )

// const App = () => <Auth providers={['github']} supabaseClient={supabase} />

// export default App

import { createClient } from '@supabase/supabase-js'
import { useRouter } from 'next/router'
import { useContext } from 'react'
import { useSession, useSupabaseClient } from '@supabase/auth-helpers-react'
import Head from 'next/head'
import { Auth, ThemeSupa } from '@supabase/auth-ui-react'

export default function Contact() {
  const session = useSession()
  const router = useRouter()
  const supabaseClient = useSupabaseClient()

  const supabase = createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY
  )

  if(session)router.push('/')

  return (
    <div>
      <Head>
        <title>WebTech - user signin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Auth
        supabaseClient={supabaseClient}
        appearance={{ theme: ThemeSupa }}
        providers={['github']}
      />
    </div>
  )
}