import { useRouter } from 'next/router'
import { useSupabaseClient } from '@supabase/auth-helpers-react'
import Head from 'next/head'
import { Auth, ThemeSupa } from '@supabase/auth-ui-react'
import UserContext from '../components/UserContext'
import { useContext } from 'react'

export default function Contact() {
  const { user } = useContext(UserContext)
  const router = useRouter()
  const supabaseClient = useSupabaseClient()
  if(user)router.push(`/profile/${user.id}`)
  return (
    <div>
      <Head>
        <title>WebTech - user signin</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Auth
        supabaseClient={supabaseClient}
        appearance={{ theme: ThemeSupa }}
        providers={['github']}
      />
    </div>
  )
}