import { useState, useEffect } from 'react'
import Head from 'next/head'
import Link from 'next/link'
import { useSupabaseClient } from '@supabase/auth-helpers-react'

export default function Articles() {
  const [articles, setArticles] = useState([])
  const supabase = useSupabaseClient()
  useEffect(() => {
    (async () => {
      let { data, error, status } = await supabase
        .from('articles')
        .select(`id, title, content`)
        setArticles(data)
    })()
  }, [supabase])
  return (
    <div>
      <Head>
        <title>WebTech - Article list</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className='wt-title'>
        Article list
      </h1>
      
      <div className="mx-auto max-w-2xl py-16 px-4 sm:py-24 sm:px-6 lg:max-w-7xl lg:px-8 bg-blue-300">
        <div className="grid grid-cols-1 gap-y-10 gap-x-6 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 xl:gap-x-8 bg-blue-500">
          {articles.map((article) => (
            <Article key={article.id} articleData={article} />
          ))}
        </div>
      </div>
      <Link href={'/articles/createArticle'}>
        <a className={"rounded-lg px-3 py-2 text-slate-700 font-medium hover:bg-blue-600 bg-blue-400 hover:text-slate-900"}>Create new article</a>
      </Link>
    </div>
  )
}

function Article({articleData}){
  return(
    <Link href={`/articles/${articleData.id}`}>
      <div className='rounded-lg hover:bg-blue-500 bg-blue-400 p-2'>
        <div className='m-2 font-bold truncate'>{articleData.title}</div>
        <div className='bg-blue-600 p-1 truncate'>{articleData.content}</div>
      </div>
    </Link>
  )
}